### PR TITLE
feat: upgrade to angular6

### PR DESCRIPTION
**Pull request by sguiheux**
Upgrade to angular 6.
It seems to work ( i just tested it by replace old ngx-md by this one )

### CODE REVIEW

**Comment by sguiheux** [comment]
I think that angular 2 and 4 and not supported anymore. Angular just support the two last major version.
Maybe you should make a major release to not break the lib for people that use angular 5.

**Comment by tanou73** [comment]
Great, I was going to make a PR too ! Merci @sguiheux ;)
@dimpu are you planning on merging it  (the error on Travis only seems to be that you run on node 6, but ngcli6 needs node >= 8.9) ?

**Comment by dimpu** [comment]
Thanks @sguiheux for the PR. I need to update docs. I will push it to npm as soon as it's done.

**Comment by dimpu** [comment]
@sguiheux. I'm seeing lot of issue with the update. Are you able to run this in your local?

**Comment by sguiheux** [comment]
@dimpu  Yes it was working on my application.
Do you have a link of something else to see issues ?

**Comment by dimpu** [comment]
Thanks, @sguiheux. It's not working for me. Anyway, there is more issue need to address with this update. Refer  https://github.com/dimpu/ngx-md/issues/135

**Pull request merged**
