### PR TITLE
Add support for Angular Universal

### PR DESCRIPTION
**Pull request by dirkgroenen**
`document` is not available during Server Side Rendering. By using the 'he' library we're no longer depending on the DOM to exist, adding support for Angular Universal.

Fixes https://github.com/dimpu/ngx-md/issues/149

### CODE REVIEW

**Comment by dirkgroenen** [comment]
Not sure what's causing CircleCI to fail. Dependencies have been included and tests run fine on a fresh environment. 
image

**Comment by dirkgroenen** [comment]
@dimpu sorry for bothering, bot any change of looking at this one?

**Comment by dirkgroenen** [comment]
@dimpu any change of getting this merged?

**Review by h3xx — APPROVED** [review]

**Comment by h3xx** [comment]
@dirkgroenen Try this:

1. Rebase off my branch h3xx:ci-use-yarn
2. Use `yarn add he` to add the package instead of `npm`. This should also update `yarn.lock`. You'll also want to undo your changes to `npm-shrinkwrap.json`.
3. Push and cross fingers.

**Pull request closed without merging**
