### PR TITLE
Update peerDependencies to work for Angular 12

### PR DESCRIPTION
**Pull request by douglascross**

### CODE REVIEW

**Comment by seidnerj** [comment]
Can we get this merged and released please?

**Comment by BramMeerten** [comment]
@dimpu can this be merged please?

**Comment by danymarques** [comment]
Waiting for this to be merged too..

**Comment by chabb** [comment]
Same here

**Comment by danymarques** [comment]
Thanks for the merge! Could you release it please?

**Comment by danymarques** [comment]
Thanks for the release!
However, you released main (v14) and for Angular 12 and 13 we still need to use master (v8). Could you please release a new patch for the v8?

**Comment by florenceCr95** [comment]
I'm also waiting on a release for Angular 12 and 13

**Pull request merged**
