### PR TITLE
fix(markdown.service): Fix rollup issue with marked library

### PR DESCRIPTION
**Pull request by paullryan**
fixes https://github.com/dimpu/angular2-markdown/issues/108

### CODE REVIEW

**Comment by paullryan** [comment]
@dimpu Looks like the travis build is failing because of some hiccup on travis, anyway you can relaunch it.

**Comment by paullryan** [comment]
@dimpu Ok I fixed your tests, travis is happy now

**Comment by dimpu** [comment]
@paullryan Thanks For the PR but I see there are some conflicts. Can you fix them also remove yarn.lock or add it .gitignore

**Comment by paullryan** [comment]
There are no conflicts and I'd be happy to add to the .gitignore, but why? It doesn't effect a raw npm build and gives some really nice version checks for those of us using yarn...

**Pull request closed without merging**
